alter session set "_ORACLE_SCRIPT"=true;

CREATE ROLES Contabilidad;
CREATE ROLES Ventas;
CREATE ROLES IT;
CREATE ROLES Gerencia;

GRANT SELECT,INSERT ON ZAPATERIA.Cliente TO Contabilidad;
GRANT SELECT,INSERT ON ZAPATERIA.Cliente TO Ventas;
GRANT SELECT,DELETE ON ZAPATERIA.Cliente TO IT;
GRANT SELECT,INSERT,DELETE,UPDATE ON ZAPATERIA.Cliente TO Gerencia;

GRANT SELECT,INSERT ON ZAPATERIA.Vendedor TO Contabilidad;
GRANT SELECT,INSERT ON ZAPATERIA.Vendedor TO Ventas;
GRANT SELECT,DELETE ON ZAPATERIA.Vendedor TO IT;
GRANT SELECT,INSERT,DELETE,UPDATE ON ZAPATERIA.Vendedor TO Gerencia;

GRANT SELECT,INSERT ON ZAPATERIA.Producto TO Contabilidad;
GRANT SELECT,INSERT ON ZAPATERIA.Producto TO Ventas;
GRANT SELECT,DELETE ON ZAPATERIA.Producto TO IT;
GRANT SELECT,INSERT,DELETE,UPDATE ON ZAPATERIA.Producto TO Gerencia;

GRANT SELECT,INSERT ON ZAPATERIA.Factura TO Contabilidad;
GRANT SELECT,INSERT ON ZAPATERIA.Factura TO Ventas;
GRANT SELECT,DELETE ON ZAPATERIA.Factura TO IT;
GRANT SELECT,INSERT,DELETE,UPDATE ON ZAPATERIA.Factura TO Gerencia;

GRANT SELECT,INSERT ON ZAPATERIA.Detalle TO Contabilidad;
GRANT SELECT,INSERT ON ZAPATERIA.Detalle TO Ventas;
GRANT SELECT,DELETE ON ZAPATERIA.Detalle TO IT;
GRANT SELECT,INSERT,DELETE,UPDATE ON ZAPATERIA.Detalle TO Gerencia;


GRANT CREATE USER, CREATE TABLE TO IT;
GRANT CREATE USER TO Gerencia;



CREATE USER Contabilidad1 IDENTIFIED BY bd2Conta1 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER Contabilidad2 IDENTIFIED BY bd2Conta2 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER Ventas1 IDENTIFIED BY bd2Ventas1 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER Ventas2 IDENTIFIED BY bd2Ventas2 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER IT1 IDENTIFIED BY bd2IT1 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER IT2 IDENTIFIED BY IT2 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER Gerencia1 IDENTIFIED BY bd2Gerencia1 DEFAULT TABLESPACE TSZAPATERIA;
CREATE USER Gerencia2 IDENTIFIED BY bd2Gerencia2 DEFAULT TABLESPACE TSZAPATERIA;  

GRANT CREATE SESSION TO Contabilidad1;
GRANT CREATE SESSION TO Contabilidad2;
GRANT CREATE SESSION TO Ventas1;
GRANT CREATE SESSION TO Ventas2;
GRANT CREATE SESSION TO IT1;
GRANT CREATE SESSION TO IT2;
GRANT CREATE SESSION TO Gerencia1;
GRANT CREATE SESSION TO Gerencia2;


GRANT Contabilidad TO Contabilidad1;
GRANT Ventas TO Ventas1;
GRANT IT TO IT1;
GRANT Gerencia TO Gerencia1;

GRANT Contabilidad TO Contabilidad2;
GRANT Ventas TO Ventas1 ; 
GRANT IT TO IT1;
GRANT Gerencia TO Gerencia1;